### ISSUE TITLE
MongoDB option

### ISSUE THREAD

**Issue by jh3y** [jh3y/tyto#37]
Had an email out of the blue earlier today about installing tyto onto a Debian machine and using from different locations but hoped for some kind of database connections.

Proposal is to allow user to install MongoDB on their own accord but add a flag to the config which will allow the user to set whether using DB. If so set up a local database on the machine being built on.

In addition to this, add testing for new server requests using sinon for AJAX stubbing.

@jh3y

**Comment by jh3y** [comment]
Started looking into a document structure for this and am thinking a Collection of Users and a Collection of boards with a relationship between them. This should make sense as boards shouldn't be sharing cards but boards could share users and vice versa.

@jh3y

**Comment by jh3y** [comment]
New MV* implementation from `2.0.0` will make __tyto__ easy enough hopefully to migrate to a peristent DB backend on a server so this issue should be no longer relevant.

Possible alter docs to explain possible migration steps.

@jh3y

**Comment by n00b42** [comment]
Has such a migration been implemented? (Really like the project but would need to access it from different locations)

**Comment by jh3y** [comment]
Hey @n00b42 

I'm afraid I've still not made an attempt at this integration :cry:

I still believe it wouldn't be too troublesome though :smile:

The project currently uses a localStorage adapter which I think could be swapped out if a database was in place. I don't think it necessarily has to be `mongo` either.

However, chances are that next time I get to invest some time in the project I will likely rewrite it again.

@jh3y

**Comment by n00b42** [comment]
Meaning, should try something on my own or that either way it will break with the next "update"? :)

**Comment by jh3y** [comment]
Ahh no not at all :smile: 

I tend to change major parts when investing time into `tyto` as I see it as an opportunity to try different libraries etc. For instance, the last rewrite introduced `Backbone`and `Marionette` 😄 

I was contemplating the use of `elasticsearch` for persistence.

@jh3y
