### ISSUE TITLE
No option to Add/Create a board

### ISSUE THREAD

**Issue by rahulsh1** [jh3y/tyto#53]
I followed the readme instructions and installed this. When I open the `http://localhost:1987/public/` page, I dont see an option to create a New board. Clicking on left menu shows an empty page. On the browser console, I see 

    Uncaught UndefinedTemplateError: Cannot render the template since it is null or undefined.  vendor.min.js:54

**Comment by jh3y** [comment]
Hey there @rahulsh1 

I've just done a fresh clone of the repo. I then followed the steps; `npm install` folllowed by `bower install`(this step does take some time gathering assets) and ran `gulp` and I didn't face any issues. My page opened up presented with the cookie banner and option to "Add a board" or "Load the intro board".

From the looks of that error. There is something that hasn't properly compiled or there is a vendor source missing. I'd reccomend trying to install assets with `bower install` again.

@jh3y

**Comment by rahulsh1** [comment]
JFYI, I am building this on `Windows 7`. I'll dig in more to see if `npm install` or `bower install` throw any errors.

**Comment by ersingenel** [comment]
I have same issue: 
Uncaught UndefinedTemplateError: Cannot render the template since it is null or undefined.

**Comment by ersingenel** [comment]
I fixed it by changing base variable in gulpfile.js

```
gulp.task('tmpl:compile', function(){
  return gulp.src(sources.templates)
    .pipe(plugins.plumber())
    .pipe(plugins.jade(pluginOpts.jade))
    .pipe(plugins.template({
      name: 'templates.js',
      base: 'src\\jade\\templates\\', 
      variable: 'module.exports'
    }))
    .pipe(gulp.dest(destinations.templates));
});
```

**Comment by jh3y** [comment]
Hi @ersingenel ,

Good spot there! I'm using OSX and as you found, Windows path wasn't being used for `gulp-template-store` base option. I've added a check using `os.platform()` although I'm not quite sure this is optimal. It doesn't quite feel right. It may be that the implementation for `gulp-template-store` needs to change so that the `os` check isn't required.

@jh3y

**Comment by rahulsh1** [comment]
Awesome. Works like a charm
