### ISSUE TITLE
Suggestions Feature

### ISSUE THREAD

**Issue by n00b42** [jh3y/tyto#60]
I stumbled over the suggestions feature when I went through the code and still wonder if it actually should work already and how? If I read correctly it is (only) activated by pressing "End" Button.

Doing that in Firefox opens the suggestions box for half a second, keeping it pressed works for a moment longer but then it begins to flicker (fast toggle), pressing it rapidly eventually yields the suggestion box staying open (what I think is the inteded way).

1. I think the bug is somehow related to key press/keydown etc events and probably some race conditions....

2. Add the Suggestions feature to the doc: that it exists and how to activate it.

**Comment by jh3y** [comment]
Hey @n00b42 

The suggestions feature is something that comes from Github flavoured markdown. I've added a line to the `README` about this. To use `Suggestions`, type the `#` key within a task description and suggestions will render. I tested this out in both Firefox and Chrome and it was working as expected 😄 

Hope that helps!

@jh3y
