### ISSUE TITLE
Setting an empty title yields it uneditable

### ISSUE THREAD

**Issue by n00b42** [jh3y/tyto#61]
Setting an empty title yields it uneditable for inplace editing
Applies for columns and tasks.
(However, tasks can still be titled again by using the edit interface and "guessing" where the titlebox is)

**Comment by jh3y** [comment]
Hey @n00b42 

I've made a small change which will make it so the title can be clicked even when empty. It just needed a `min-width` set as it's `inline-block`.

@jh3y
