### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by n00b42** [jh3y/tyto#62]
The Setup Procedure:
```
git clone https://github.com/jh3y/tyto.git
cd tyto
npm install
bower install
gulp
```
does not work anymore.

If I got it right, "bower" was removed.

But besides that there seems to be something else missing now
```
"view.ui.columnContainer.sortable is not a function"
"view.ui.taskContainer.sortable is not a function"
[...]
```

**Comment by jh3y** [comment]
I've just run the setup again to double-check. It does work but you'll need to remove your current set of installed node modules and begin the set up from scratch. I'd strongly recommend using `yarn` so that you can take advantage of the `Lockfile`.

Hope that helps!

@jh3y

**Comment by n00b42** [comment]
Thought that as well, therefore made a complete new directory/clone and did a fresh "npm install", but still had some issues... maybe some of the global npm packages? Will check if they are up to date...
Maybe you have some (additionally) installed globally?
