### ISSUE TITLE
embedding images

### ISSUE THREAD

**Issue by kasparsj** [jh3y/tyto#66]
Hi Jhey,
I'm trying to add an image to a task using this markdown syntax:
```
![google]
 (http://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png)
```
is it supposed to work?

**Comment by jh3y** [comment]
Hey @kasparsj 👋 

Thanks for raising an issue. This does work for me but I needed to remove the space between `![google]` and `(http://`.

```
![google](http://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png)
```

It's a big image though so it didn't fit inside the container 😅  Maybe an opportunity there to add some CSS for ensuring image max width is 100%.

@jh3y

**Comment by kasparsj** [comment]
Nice, thanks!

**Comment by jh3y** [comment]
Added some styling rules in new release that will ensure images are centre aligned and no bigger than 100% in width 👍
