### ISSUE TITLE
Support of tree like structure - Multiple boards

### ISSUE THREAD

**Issue by kmelnikov** [jh3y/tyto#8]
Hi jh3y, 

Thanks for the great tool!

I wonder if it is possible easily add more complex structure to the project. In particular it would be nice to have items on the panel that are actually links to other boards.

For example,  the json in that case can looks like

[{
"id": 1,
"parent": 0,
"columns":[
	{"title":"column","items":[{"content":"this is a new item"}]},
	{"title":"new column","items":[{"type": "tyto-board", "content": "text for the link", "tyto_id": 2}]},

},
{
"id": 2,
"parent": 1
"columns":[]
}
]

Do you like the idea? )

**Comment by jh3y** [comment]
I know it has certainly been some time since this issue was brought up but as a heads up I'm currently re-implementing the project using Backbone and Marionette and therefore the ability to create multiple boards will shortly be available.

@jh3y

**Comment by jh3y** [comment]
#45 provides the ability to create multiple boards but I will need to look into a way to dynamically add links between boards with some sort of typeahead like with issues here after typing #.

@jh3y
